### ISSUE TITLE
Release v1.2.1 not available in bioconda?

### ISSUE THREAD

**Issue by max1c** [FePhyFoFum/phyx#158]
Can this please be added?

**Comment by josephwb** [comment]
We are not doing anything ourselves with bioconda.Perhaps @druvus can help? AFAIK updates were supposed to be [handled by the Bioconda bot](https://github.com/FePhyFoFum/phyx/issues/60#issuecomment-717367881).

BTW a new release will be, er, released imminently, so it would be good to know what the issue is with the updating.

**Comment by max1c** [comment]
Yes, it looks like the bioconda bot is not picking them up. Hopefully someone can take a look.
