### ISSUE TITLE
Segmentation fault (core dumped) error when using the (-m) option of pxseqgen

### ISSUE THREAD

**Issue by jfwalker** [FePhyFoFum/phyx#25]
./pxseqgen -t your_tree.tre -o outfile.txt -m .33,.33,.33,.33,.33,2,.3,.3,.2,.5,.4

**Comment by josephwb** [comment]
You are missing 2 substitution parameters in the call above. Nevertheless, an error should be returned instead of a segfault. Should be a very easy fix.
We might want to change how args are passed here. I think maybe they should be separated, say: -m for the background model, then -m2 for the model beginning at node 2, etc. But I'll fix this as it is now setup first.

**Comment by josephwb** [comment]
Fixed with d93435963899ed0afff294031241c6e1d627e12a. However, in implementing the check it is clear that this setup is very clunky. Should return to alter this at some point.
