### ISSUE TITLE
pxrlt issues with non-matching errors

### ISSUE THREAD

**Issue by NatJWalker-Hale** [FePhyFoFum/phyx#85]
This may be related to the previous issue. When using pxrlt on IQ-TREE newicks with support values, it recognises support values as labels which are not in the taxon name files, and does not change the name, merely prints the original tree with original names.

**Comment by NatJWalker-Hale** [comment]
[current_names.txt](https://github.com/FePhyFoFum/phyx/files/2027543/current_names.txt)
[new_names.txt](https://github.com/FePhyFoFum/phyx/files/2027544/new_names.txt)

[cary_adh_canonical_1_cln.treefile.txt](https://github.com/FePhyFoFum/phyx/files/2027549/cary_adh_canonical_1_cln.treefile.txt)

here are the name files and the newick, but actually now I have just tried to reproduce after getting the same error a bunch of times I still get the 'label not recognised' for the internal labels, but it is printing the desired tree. So not really an issue.

**Comment by josephwb** [comment]
Ok this is because the support values are stored as names (and not annotations). 

This is annoying behaviour. I turned off the warnings for the internal labels (with 98a115c69e5611c7c0c730619271aa66274151b6). Frankly, we (I) shouldn't necessarily be expecting for _all_ labels to require changes (e.g., if we know only certain ones are funky).

Thanks for pointing this out. I will fix it once I figure out the best behaviour. I think complaining that a name doesn't match is useful. But doing some will require a different approach (i.e., looping over the names rather than the nodes).

**Comment by NatJWalker-Hale** [comment]
No problems, thanks for taking a look at it!

**Comment by josephwb** [comment]
Hey everyone. What do you think the policy on reporting 'bad' names should be? It is complicated if [trees are not complete](https://github.com/FePhyFoFum/phyx/commit/b6e140d8c3cf173fb29863525086bbd2ac5e68be). Should we just _not_ report bad names? Was trying to be helpful to user. But *nix approach would seem to be 'you are supposed to know what you are doing' and so would not report on a proposed replace that doesn't exist.

Feel like I am _way_ overthinking this. Maybe allow the existing 'error' reporting if a verbose flag is used.

**Comment by josephwb** [comment]
Should be done with 9abfb52b701af0e0b2008da618d97c91adea7d92. Only reports non-matching original names passed in, and only if verbose is turned on. Should do same with `pxrls`.
