### ISSUE TITLE
Pxrr couln't be complied correctly

### ISSUE THREAD

**Issue by sumoumouElin** [FePhyFoFum/phyx#93]
I have installed Phyx successfully following the steps,but I didn't find 'pxrr' in this package after compiling. (Linux install)

When I was in the path of 'phyx/src', I used './configure' and 'make' respectively. However, I found that only some of softwares (pxclsq,pxcat,pxs2phy,pxs2nex and so on) could be compiled correctly and ran successfully, but 'pxrr' failed to be complied. Or, in other words, when the package is compiled, it seems to skip pxrr directly.

**Comment by josephwb** [comment]
I don't understand what could have gone wrong. `pxrr` is in the list of default make targets. I just did a fresh clone/compile and things went as expected.

Did compilation obviously fail and stop. It could be a dependency, and compilation stopped before getting to `pxrr`.

How about this? What happens if you do:

``make pxrr``

**Comment by sumoumouElin** [comment]
Thank your for your help! pxrr can be complied correctly now.

**Comment by josephwb** [comment]
Great! I'd still like to de able to diagnose the problem if possible. Any ideas?

**Comment by josephwb** [comment]
@sumoumouElin Do you know which programs got compiled initially? It could help figure out what went wrong (e.g., if it stopped on a certain program).
