### ISSUE TITLE
Install errors on OSX and Ubuntu

### ISSUE THREAD

**Issue by fishextinction** [FePhyFoFum/phyx#99]
Attempted to install phyx on Ubuntu 18.04.2 LTS

I note that this software appears to be designed for Python 2.7, but the guide provides no instructions on how to make sure modules are installed in a such a way that they are actually installed under 2.7.

Running python run_tests.py:

>   File "run_tests.py", line 18
>     print "TESTING",name
>                   ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print("TESTING",name)?
> 

If I run "python2.7 run_tests.py" I get a giant stream of text that completely fills up the terminal, but the bottom says:

> PASSED TESTS: 31
> FAILED TESTS: 9
> These failed:
> 	pxmrcacut,pxt2new,pxcolt,pxtscale,pxrlt,pxrmk,pxrmt,pxrr,pxmrcaname
> 

I briefly attempted in install on OS X 10.13.6 and get the same errors. Why did these fail and what to do next?

**Comment by josephwb** [comment]
Sorry for the difficulties.

The only involvement of python is script-wise and (like a bash script) checks the expected output of the various programs (there are ~40). You are correct in that the script expects python 2.7.

The giant stream of text is an expected output of this testing process.

The fact that so many programs _fail_ testing testing is due to a recent change in the precision of the edge length parameters. We (on our side) need only change the expected outputs to make the tests pass. So, nothing to worry about.

**Comment by minutoides** [comment]
I've the same problem... 9 test failed, and when i'm looking for these files like pxrr it doesn't appears in the directory... any solution?

**Comment by minutoides** [comment]
Hi! Thanks for the aportation.
I'm having the same problem, 9 failed test, when I look for the files inside the src folder they do not appear, these are the files: pxcolt,pxmrcacut,pxmrcaname,pxrlt,pxrmk,pxrmt,pxrr,pxt2new,pxtscale. 
There is another way to install this files individualy or another way to repair the phyx package?
Thanks, Miguel

**Comment by josephwb** [comment]
As I mentioned in the closing comment, these are not real failures. Rather, it is a change in the precision used. We just need to update the expected results and these failures will disappear. I'll do this soon. Sorry that that was not clear.

I'm not sure what the issue is with pxrr & others. Do things seem to compile completely? It sounds like maybe things crash part way through. You can certainly compile an individual program (e.g., pxrr) by doing:
```
make pxrr
```
But ideally we would figure out what is going wrong. Can you do:
```
make clean && make
```
and post all of the output produced?
